### ISSUE TITLE
Duplicated paragraph in section 3

### ISSUE THREAD

**Issue by RBastianini** [tajmone/polygen-docs#40]
In **§3.1**
There are two different version of the same paragraph
> Keep in mind then that it is up to you [...]

and

> Bare in mind that you’ll need to provide [...]

I think the second one flows better. I would also suggest to change
> Bare in mind that you’ll need to provide a non-recursive production somewhere along the line, in order to guarantee to the program an exit point from the recursion, at one point or another; otherwise, a cyclic recursion error will be generated by the grammar checker (see section 4.1.2).

to

> Bear in mind that you’ll need to provide a non-recursive production somewhere along the line, in order to guarantee an exit point from the recursion, at some point; otherwise, a cyclic recursion error will be generated by the grammar checker (see section 4.1.2).

**Comment by tajmone** [comment]
I think you're looking at the original (unedited) version of the document; this issue was already pointed out and fixed last week.

The correct preview link for v1.1.1-rc is (see #27):

- https://htmlpreview.github.io/?https://github.com/tajmone/polygen-docs/blob/dev1.1.1_EN/docs-src/polygen-spec_EN.html

and for the Italian version:

- https://htmlpreview.github.io/?https://github.com/tajmone/polygen-docs/blob/dev1.1.1_IT/docs-src/polygen-spec_IT.html

I've now changed "from the recursion, at one point or another; otherwise," &rarr; "from the recursion, at one point; otherwise,".
